### ISSUE TITLE
Crash on load: NoClassDefFoundError

### ISSUE THREAD

**Issue by jackatthekilns** [BTW-Community/Deco-Addon-2#46]
Deco 3.0.2 with CE 1.2.1
 Here is the log
MultiMC version: 0.6.13-2517

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.249.115.75]

session.minecraft.net resolves to:
    [52.44.210.220, 34.192.50.106, 3.234.0.54]

textures.minecraft.net resolves to:
    [13.249.109.106, 13.249.109.129, 13.249.109.98, 13.249.109.21]

api.mojang.com resolves to:
    [13.249.107.137]

Minecraft folder is:
C:/Users/User/Dropbox/MultiMC/Better than Wolves Modded/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_311/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_311, using 64-bit architecture, from Oracle Corporation.

Main Class:
  

Native path:
  C:/Users/User/Dropbox/MultiMC/Better than Wolves Modded/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  C:/Users/User/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/User/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/User/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/User/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/User/Dropbox/MultiMC/Better than Wolves Modded/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/User/Downloads/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/User/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Jar Mods:
  BTW-CE-1.2.1-client (540903db-b889-4820-9212-2028b779af64.jar)
  BetterTerrainAddon-2.0.4-client (bd467031-0eb1-4dec-af57-ad8d164ceabd.jar)
  DecoAddon-3.0.2-client (b9c9cdd1-183a-4380-929a-896ab98781ae.jar)
  HCSpawnConfigv1.1 (483b33b0-c606-4965-a238-ae667432f84b.jar)
  LightningTweaker-1.1.1-client (57ae9a52-eea5-4e6b-a4ec-d038b69ca636.jar)
  CraftGuide-NoLoader-MC152 - BTW Fixed - V3-exp (b8090e54-bb2f-40fd-9788-de603591778d.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 11212

Using onesix launcher.

Launching with applet wrapper...

MCPatcherUtils initialized:
Minecraft directory: C:\Users\User\AppData\Roaming\.minecraft
  (assets, libraries, versions)
Game directory:      C:\Users\User\AppData\Roaming\.minecraft
  (resourcepacks, saves)
Minecraft version:   1.5.2
MCPatcher version:   5.0.3
Max heap memory:     1820.5MB
Max direct memory: 1820.5MB
WARNING: configuration file C:\Users\User\AppData\Roaming\.minecraft\mcpatcher.json not found, using defaults
WARNING: could not determine selected profile, defaulting to MCPatcher
Launcher profile:  MCPatcher

Exception in thread "main" java.lang.NoClassDefFoundError: FCBlockPotato
	at apa.<clinit>(Block.java:207)
	at kf.a(StatList.java:187)
	at kf.<clinit>(StatList.java:87)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:294)
	at avv.<init>(SourceFile:38)
	at net.minecraft.client.MinecraftApplet.init(SourceFile:38)
	at net.minecraft.Launcher.init(Launcher.java:109)
	at org.multimc.LegacyFrame.start(LegacyFrame.java:130)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:131)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: FCBlockPotato
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Clipboard copy at: 23 Oct 2021 18:33:12 -0400

**Comment by ammoore00** [comment]
Fixed for next release :)
